[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--production=false"

# Remove the problematic plugin temporarily
# [[plugins]]
#   package = "@netlify/plugin-nextjs"
